# Pattern Recognition
## Computer Homework 2
## Ehsan Kouchaki
### Dec. 2, 2021
####

### Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Functions

In [2]:
# Euclidean distance
def euclidean(x, X):
    x_X = x - X
    return np.sqrt(np.diag(x_X@x_X.T))

## Excercise 1 - Iris data

In [3]:
df = pd.read_fwf('Iris-Data_dat.txt', header=None)
data_iris = df.to_numpy()

confusion_iris_1NN = np.zeros((3, 3))
confusion_iris_2NN = np.zeros((3, 3))
confusion_iris_3NN = np.zeros((3, 3))
for i in range(150):
    train_data_iris = np.delete(data_iris, (i), axis=0)
    if (i < 50):
        train_data_iris_c1 = train_data_iris[0:49]
        train_data_iris_c2 = train_data_iris[49:99]
        train_data_iris_c3 = train_data_iris[99:149]
    elif (i >= 50 and i < 100):
        train_data_iris_c1 = train_data_iris[0:50]
        train_data_iris_c2 = train_data_iris[50:99]
        train_data_iris_c3 = train_data_iris[99:149]
    else:
        train_data_iris_c1 = train_data_iris[0:50]
        train_data_iris_c2 = train_data_iris[50:100]
        train_data_iris_c3 = train_data_iris[100:149]
    
    N1 = len(train_data_iris_c1)
    N2 = len(train_data_iris_c2)
    N3 = len(train_data_iris_c3)
    
    xi = data_iris[i][1:5]
    label = data_iris[i][0]
    X_c1 = train_data_iris_c1[:,1:5]
    X_c2 = train_data_iris_c2[:,1:5]
    X_c3 = train_data_iris_c3[:,1:5]
        
    dist_c1 = euclidean(xi, X_c1)
    dist_c2 = euclidean(xi, X_c2)
    dist_c3 = euclidean(xi, X_c3)
    
    for k in ([1, 2, 3]):
        V1 = np.sort(dist_c1)[k - 1]
        V2 = np.sort(dist_c2)[k - 1]
        V3 = np.sort(dist_c3)[k - 1]
    
        c_pr = np.argmin([N1*V1, N2*V2, N3*V3]) + 1
    
        if (c_pr != label):
            print('Sample no.{}, with {}NN,  from class {} incorrectly classified to class {}'
                  .format(i + 1, k, label, c_pr))
            if (k == 1): confusion_iris_1NN[label - 1][c_pr - 1] += 1
            if (k == 2): confusion_iris_2NN[label - 1][c_pr - 1] += 1
            if (k == 3): confusion_iris_3NN[label - 1][c_pr - 1] += 1
            
for i in range(3):
    confusion_iris_1NN[i][i] = 50 - np.sum(confusion_iris_1NN[i])
    confusion_iris_2NN[i][i] = 50 - np.sum(confusion_iris_2NN[i])
    confusion_iris_3NN[i][i] = 50 - np.sum(confusion_iris_3NN[i])
confusion_matrix_iris_1NN = pd.DataFrame(confusion_iris_1NN, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])
confusion_matrix_iris_2NN = pd.DataFrame(confusion_iris_2NN, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])
confusion_matrix_iris_3NN = pd.DataFrame(confusion_iris_3NN, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for 1NN is:')
    print(confusion_matrix_iris_1NN)
    print('\n Confusion matrix for 2NN is:')
    print(confusion_matrix_iris_2NN)
    print('\n Confusion matrix for 3NN is:')
    print(confusion_matrix_iris_3NN)
    
print('\nThe error rate of 1NN is: ', (150 - np.trace(confusion_iris_1NN))/150)
print('The error rate of 2NN is: ', (150 - np.trace(confusion_iris_2NN))/150)
print('The error rate of 3NN is: ', (150 - np.trace(confusion_iris_3NN))/150)

Sample no.71, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.71, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.71, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.73, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.73, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.73, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.84, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.84, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.84, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.107, with 1NN,  from class 3 incorrectly classified to class 2
Sample no.107, with 2NN,  from class 3 incorrectly classified to class 2
Sample no.107, with 3NN,  from class 3 incorrectly classified to class 2
Sample no.120, with 1NN,  from class 3 incorrectly classified to class 2
Sample no.120, with 2NN,  from class 3 incorrectly classified to class 2
Sample no.120, with 3NN,  from class 3 incorrectly classified to class 2
Sample no.134, with 1NN,  from class 3 incorrectly classified to class 2
Sample no.134, with 2NN,  from class 3 incorrectly classified to class 2

 Confusion matrix for 1NN is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           50.0            0.0            0.0
c2(actual)            0.0           47.0            3.0
c3(actual)            0.0            3.0           47.0

 Confusion matrix for 2NN is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           50.0            0.0            0.0
c2(actual)            0.0           47.0            3.0
c3(actual)            0.0            3.0           47.0

 Confusion matrix for 3NN is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           50.0            0.0            0.0
c2(actual)            0.0           47.0            3.0
c3(actual)            0.0            2.0           48.0

The error rate of 1NN is:  0.04
The error rate of 2NN is:  0.04
The error rate of 3NN is:  0.03333333333333333

## Excercise 1 - Liquid data

In [4]:
df = pd.read_fwf('Liquid-Data_dat.txt', header=None)
data_liquid = df.to_numpy()

confusion_liquid_1NN = np.zeros((3, 3))
confusion_liquid_2NN = np.zeros((3, 3))
confusion_liquid_3NN = np.zeros((3, 3))
for i in range(178):
    train_data_liquid = np.delete(data_liquid, (i), axis=0)
    if (i < 59):
        train_data_liquid_c1 = train_data_liquid[0:58]
        train_data_liquid_c2 = train_data_liquid[58:129]
        train_data_liquid_c3 = train_data_liquid[129:178]
    elif (i >= 59 and i < 130):
        train_data_liquid_c1 = train_data_liquid[0:59]
        train_data_liquid_c2 = train_data_liquid[59:129]
        train_data_liquid_c3 = train_data_liquid[129:178]
    else:
        train_data_liquid_c1 = train_data_liquid[0:59]
        train_data_liquid_c2 = train_data_liquid[59:130]
        train_data_liquid_c3 = train_data_liquid[130:178]
     
    N1 = len(train_data_liquid_c1)
    N2 = len(train_data_liquid_c2)
    N3 = len(train_data_liquid_c3)
    
    xi = data_liquid[i][1:7]
    label = data_liquid[i][0]
    X_c1 = train_data_liquid_c1[:,1:7]
    X_c2 = train_data_liquid_c2[:,1:7]
    X_c3 = train_data_liquid_c3[:,1:7]
        
    dist_c1 = euclidean(xi, X_c1)
    dist_c2 = euclidean(xi, X_c2)
    dist_c3 = euclidean(xi, X_c3)
    
    for k in ([1, 2, 3]):
        V1 = np.sort(dist_c1)[k - 1]
        V2 = np.sort(dist_c2)[k - 1]
        V3 = np.sort(dist_c3)[k - 1]
    
        c_pr = np.argmin([N1*V1, N2*V2, N3*V3]) + 1
    
        if (c_pr != label):
            print('Sample no.{}, with {}NN,  from class {} incorrectly classified to class {}'
                  .format(i + 1, k, label, c_pr))
            if (k == 1): confusion_liquid_1NN[label - 1][c_pr - 1] += 1
            if (k == 2): confusion_liquid_2NN[label - 1][c_pr - 1] += 1
            if (k == 3): confusion_liquid_3NN[label - 1][c_pr - 1] += 1
            
confusion_liquid_1NN[0][0] = 59 - np.sum(confusion_liquid_1NN[0])
confusion_liquid_1NN[1][1] = 71 - np.sum(confusion_liquid_1NN[1])
confusion_liquid_1NN[2][2] = 48 - np.sum(confusion_liquid_1NN[2])

confusion_liquid_2NN[0][0] = 59 - np.sum(confusion_liquid_2NN[0])
confusion_liquid_2NN[1][1] = 71 - np.sum(confusion_liquid_2NN[1])
confusion_liquid_2NN[2][2] = 48 - np.sum(confusion_liquid_2NN[2])

confusion_liquid_3NN[0][0] = 59 - np.sum(confusion_liquid_3NN[0])
confusion_liquid_3NN[1][1] = 71 - np.sum(confusion_liquid_3NN[1])
confusion_liquid_3NN[2][2] = 48 - np.sum(confusion_liquid_3NN[2])

confusion_matrix_liquid_1NN = pd.DataFrame(confusion_liquid_1NN, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])
confusion_matrix_liquid_2NN = pd.DataFrame(confusion_liquid_2NN, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])
confusion_matrix_liquid_3NN = pd.DataFrame(confusion_liquid_3NN, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for 1NN is:')
    print(confusion_matrix_liquid_1NN)
    print('\n Confusion matrix for 2NN is:')
    print(confusion_matrix_liquid_2NN)
    print('\n Confusion matrix for 3NN is:')
    print(confusion_matrix_liquid_3NN)
    
print('\nThe error rate of 1NN is: ', (178 - np.trace(confusion_liquid_1NN))/178)
print('The error rate of 2NN is: ', (178 - np.trace(confusion_liquid_2NN))/178)
print('The error rate of 3NN is: ', (178 - np.trace(confusion_liquid_3NN))/178)

Sample no.61, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.61, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.62, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.62, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.62, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.63, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.63, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.63, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.66, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.66, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.66, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.67, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.68, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.68, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.68, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.69, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.69, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.69, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.71, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.71, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.73, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.74, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.74, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.74, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.75, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.77, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.82, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.82, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.82, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.84, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.84, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.84, with 3NN,  from class 2 incorrectly classified to class 3
Sample no.96, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.99, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.99, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.113, with 1NN,  from class 2 incorrectly classified to class 3
Sample no.113, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.122, with 2NN,  from class 2 incorrectly classified to class 3
Sample no.122, with 3NN,  from class 2 incorrectly classified to class 3

 Confusion matrix for 1NN is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           59.0            0.0            0.0
c2(actual)            3.0           59.0            9.0
c3(actual)            0.0            0.0           48.0

 Confusion matrix for 2NN is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           59.0            0.0            0.0
c2(actual)            4.0           57.0           10.0
c3(actual)            0.0            0.0           48.0

 Confusion matrix for 3NN is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           59.0            0.0            0.0
c2(actual)            6.0           58.0            7.0
c3(actual)            0.0            0.0           48.0

The error rate of 1NN is:  0.06741573033707865
The error rate of 2NN is:  0.07865168539325842
The error rate of 3NN is:  0.07303370786516854

## Excercise 1 - Normal data (train data)

In [5]:
df = pd.read_fwf('Normal-Data-Training_dat.txt', header=None)
data_normal = df.to_numpy()

confusion_normal_1NN = np.zeros((2, 2))
confusion_normal_2NN = np.zeros((2, 2))
confusion_normal_3NN = np.zeros((2, 2))
for i in range(1000):
    train_data_normal = np.delete(data_normal, (i), axis=0)
    if (i < 500):
        train_data_normal_c1 = train_data_normal[0:499]
        train_data_normal_c2 = train_data_normal[499:999]
    else:
        train_data_normal_c1 = train_data_normal[0:500]
        train_data_normal_c2 = train_data_normal[500:999]
        
    N1 = len(train_data_normal_c1)
    N2 = len(train_data_normal_c2)
    
    xi = data_normal[i][1:3]
    label = int(data_normal[i][0])
    X_c1 = train_data_normal_c1[:,1:3]
    X_c2 = train_data_normal_c2[:,1:3]
        
    dist_c1 = euclidean(xi, X_c1)
    dist_c2 = euclidean(xi, X_c2)
    
    for k in ([1, 2, 3]):
        V1 = np.sort(dist_c1)[k - 1]
        V2 = np.sort(dist_c2)[k - 1]
    
        c_pr = np.argmin([N1*V1, N2*V2]) + 1
    
        if (c_pr != label):
            print('Sample no.{}, with {}NN,  from class {} incorrectly classified to class {}'
                  .format(i + 1, k, label, c_pr))
            if (k == 1): confusion_normal_1NN[label - 1][c_pr - 1] += 1
            if (k == 2): confusion_normal_2NN[label - 1][c_pr - 1] += 1
            if (k == 3): confusion_normal_3NN[label - 1][c_pr - 1] += 1
            
for i in range(2):
    confusion_normal_1NN[i][i] = 500 - np.sum(confusion_normal_1NN[i])
    confusion_normal_2NN[i][i] = 500 - np.sum(confusion_normal_2NN[i])
    confusion_normal_3NN[i][i] = 500 - np.sum(confusion_normal_3NN[i])
    
confusion_matrix_normal_1NN = pd.DataFrame(confusion_normal_1NN, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])
confusion_matrix_normal_2NN = pd.DataFrame(confusion_normal_2NN, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])
confusion_matrix_normal_3NN = pd.DataFrame(confusion_normal_3NN, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for 1NN is:')
    print(confusion_matrix_normal_1NN)
    print('\n Confusion matrix for 2NN is:')
    print(confusion_matrix_normal_2NN)
    print('\n Confusion matrix for 3NN is:')
    print(confusion_matrix_normal_3NN)
    
print('\nThe error rate of 1NN is: ', (1000 - np.trace(confusion_normal_1NN))/1000)
print('The error rate of 2NN is: ', (1000 - np.trace(confusion_normal_2NN))/1000)
print('The error rate of 3NN is: ', (1000 - np.trace(confusion_normal_3NN))/1000)

Sample no.11, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.11, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.36, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.36, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.36, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.37, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.46, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.46, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.46, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.70, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.70, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.71, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.71, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.71, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.97, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.97, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.97, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.105, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.105, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.108, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.108, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.108, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.117, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.117, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.117, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.121, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.129, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.129, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.129, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.134, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.143, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.143, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.143, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.150, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.150, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.160, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.160, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.160, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.166, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.166, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.166, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.172, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.172, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.177, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.177, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.177, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.184, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.184, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.184, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.185, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.187, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.197, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.197, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.197, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.210, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.210, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.210, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.213, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.213, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.213, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.216, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.216, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.216, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.217, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.217, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.217, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.239, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.240, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.240, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.240, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.241, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.241, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.241, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.242, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.248, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.251, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.251, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.251, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.254, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.254, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.254, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.255, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.255, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.255, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.262, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.262, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.262, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.265, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.265, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.265, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.266, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.266, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.266, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.267, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.267, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.267, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.272, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.273, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.273, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.273, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.282, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.282, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.282, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.288, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.292, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.295, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.306, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.306, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.306, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.314, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.314, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.314, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.316, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.316, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.316, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.326, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.326, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.326, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.342, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.347, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.347, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.347, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.363, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.363, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.363, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.364, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.367, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.367, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.367, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.372, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.382, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.390, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.390, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.390, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.408, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.408, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.408, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.416, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.416, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.424, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.424, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.424, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.432, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.434, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.434, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.434, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.439, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.439, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.462, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.463, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.463, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.463, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.464, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.464, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.464, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.467, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.473, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.475, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.475, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.475, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.481, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.481, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.484, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.484, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.487, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.493, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.493, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.493, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.494, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.494, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.494, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.497, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.497, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.497, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.502, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.503, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.503, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.503, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.520, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.520, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.520, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.529, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.529, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.529, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.532, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.532, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.532, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.551, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.551, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.554, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.554, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.558, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.558, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.562, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.575, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.575, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.583, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.584, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.584, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.584, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.591, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.595, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.595, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.595, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.596, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.600, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.600, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.600, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.618, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.618, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.618, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.637, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.637, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.637, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.644, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.664, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.665, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.665, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.665, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.667, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.667, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.667, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.676, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.677, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.694, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.703, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.703, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.703, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.711, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.711, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.711, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.715, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.715, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.715, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.737, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.746, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.746, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.746, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.750, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.750, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.750, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.755, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.762, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.762, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.762, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.768, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.770, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.770, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.772, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.772, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.772, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.780, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.787, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.791, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.791, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.791, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.797, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.798, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.798, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.798, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.799, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.799, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.799, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.802, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.802, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.802, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.806, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.821, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.821, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.825, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.825, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.825, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.832, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.836, with 1NN,  from class 2 incorrectly classified to class 1

## Excercise 1 - Normal data (test data)

In [6]:
df_test = pd.read_fwf('Normal-Data-Testing_dat.txt', header=None)
data_normal = df.to_numpy()

confusion_normal_1NN = np.zeros((2, 2))
confusion_normal_2NN = np.zeros((2, 2))
confusion_normal_3NN = np.zeros((2, 2))
for i in range(1000):
    train_data_normal = np.delete(data_normal, (i), axis=0)
    if (i < 500):
        train_data_normal_c1 = train_data_normal[0:499]
        train_data_normal_c2 = train_data_normal[499:999]
    else:
        train_data_normal_c1 = train_data_normal[0:500]
        train_data_normal_c2 = train_data_normal[500:999]
        
    N1 = len(train_data_normal_c1)
    N2 = len(train_data_normal_c2)
    
    xi = data_normal[i][1:3]
    label = int(data_normal[i][0])
    X_c1 = train_data_normal_c1[:,1:3]
    X_c2 = train_data_normal_c2[:,1:3]
        
    dist_c1 = euclidean(xi, X_c1)
    dist_c2 = euclidean(xi, X_c2)
    
    for k in ([1, 2, 3]):
        V1 = np.sort(dist_c1)[k - 1]
        V2 = np.sort(dist_c2)[k - 1]
    
        c_pr = np.argmin([N1*V1, N2*V2]) + 1
    
        if (c_pr != label):
            print('Sample no.{}, with {}NN,  from class {} incorrectly classified to class {}'
                  .format(i + 1, k, label, c_pr))
            if (k == 1): confusion_normal_1NN[label - 1][c_pr - 1] += 1
            if (k == 2): confusion_normal_2NN[label - 1][c_pr - 1] += 1
            if (k == 3): confusion_normal_3NN[label - 1][c_pr - 1] += 1
            
for i in range(2):
    confusion_normal_1NN[i][i] = 500 - np.sum(confusion_normal_1NN[i])
    confusion_normal_2NN[i][i] = 500 - np.sum(confusion_normal_2NN[i])
    confusion_normal_3NN[i][i] = 500 - np.sum(confusion_normal_3NN[i])
    
confusion_matrix_normal_1NN = pd.DataFrame(confusion_normal_1NN, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])
confusion_matrix_normal_2NN = pd.DataFrame(confusion_normal_2NN, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])
confusion_matrix_normal_3NN = pd.DataFrame(confusion_normal_3NN, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for 1NN is:')
    print(confusion_matrix_normal_1NN)
    print('\n Confusion matrix for 2NN is:')
    print(confusion_matrix_normal_2NN)
    print('\n Confusion matrix for 3NN is:')
    print(confusion_matrix_normal_3NN)
    
print('\nThe error rate of 1NN is: ', (1000 - np.trace(confusion_normal_1NN))/1000)
print('The error rate of 2NN is: ', (1000 - np.trace(confusion_normal_2NN))/1000)
print('The error rate of 3NN is: ', (1000 - np.trace(confusion_normal_3NN))/1000)

Sample no.11, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.11, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.36, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.36, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.36, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.37, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.46, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.46, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.46, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.70, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.70, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.71, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.71, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.71, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.97, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.97, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.97, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.105, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.105, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.108, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.108, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.108, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.117, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.117, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.117, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.121, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.129, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.129, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.129, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.134, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.143, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.143, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.143, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.150, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.150, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.160, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.160, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.160, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.166, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.166, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.166, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.172, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.172, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.177, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.177, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.177, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.184, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.184, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.184, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.185, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.187, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.197, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.197, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.197, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.210, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.210, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.210, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.213, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.213, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.213, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.216, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.216, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.216, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.217, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.217, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.217, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.239, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.240, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.240, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.240, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.241, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.241, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.241, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.242, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.248, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.251, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.251, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.251, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.254, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.254, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.254, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.255, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.255, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.255, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.262, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.262, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.262, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.265, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.265, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.265, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.266, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.266, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.266, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.267, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.267, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.267, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.272, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.273, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.273, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.273, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.282, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.282, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.282, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.288, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.292, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.295, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.306, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.306, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.306, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.314, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.314, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.314, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.316, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.316, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.316, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.326, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.326, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.326, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.342, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.347, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.347, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.347, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.363, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.363, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.363, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.364, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.367, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.367, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.367, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.372, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.382, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.390, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.390, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.390, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.408, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.408, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.408, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.416, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.416, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.424, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.424, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.424, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.432, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.434, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.434, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.434, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.439, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.439, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.462, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.463, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.463, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.463, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.464, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.464, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.464, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.467, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.473, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.475, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.475, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.475, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.481, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.481, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.484, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.484, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.487, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.493, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.493, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.493, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.494, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.494, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.494, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.497, with 1NN,  from class 1 incorrectly classified to class 2
Sample no.497, with 2NN,  from class 1 incorrectly classified to class 2
Sample no.497, with 3NN,  from class 1 incorrectly classified to class 2
Sample no.502, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.503, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.503, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.503, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.520, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.520, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.520, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.529, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.529, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.529, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.532, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.532, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.532, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.551, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.551, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.554, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.554, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.558, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.558, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.562, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.575, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.575, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.583, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.584, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.584, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.584, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.591, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.595, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.595, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.595, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.596, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.600, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.600, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.600, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.618, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.618, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.618, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.637, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.637, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.637, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.644, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.664, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.665, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.665, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.665, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.667, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.667, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.667, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.676, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.677, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.694, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.703, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.703, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.703, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.711, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.711, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.711, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.715, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.715, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.715, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.737, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.746, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.746, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.746, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.750, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.750, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.750, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.755, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.762, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.762, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.762, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.768, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.770, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.770, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.772, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.772, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.772, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.780, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.787, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.791, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.791, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.791, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.797, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.798, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.798, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.798, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.799, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.799, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.799, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.802, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.802, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.802, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.806, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.821, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.821, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.825, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.825, with 2NN,  from class 2 incorrectly classified to class 1
Sample no.825, with 3NN,  from class 2 incorrectly classified to class 1
Sample no.832, with 1NN,  from class 2 incorrectly classified to class 1
Sample no.836, with 1NN,  from class 2 incorrectly classified to class 1

## Excercise 2 - Iris data

In [7]:
df = pd.read_fwf('Iris-Data_dat.txt', header=None)
data_iris = df.to_numpy()

confusion_iris_MMD = np.zeros((3, 3))
for i in range(150):
    train_data_iris = np.delete(data_iris, (i), axis=0)
    if (i < 50):
        train_data_iris_c1 = train_data_iris[0:49]
        train_data_iris_c2 = train_data_iris[49:99]
        train_data_iris_c3 = train_data_iris[99:149]
    elif (i >= 50 and i < 100):
        train_data_iris_c1 = train_data_iris[0:50]
        train_data_iris_c2 = train_data_iris[50:99]
        train_data_iris_c3 = train_data_iris[99:149]
    else:
        train_data_iris_c1 = train_data_iris[0:50]
        train_data_iris_c2 = train_data_iris[50:100]
        train_data_iris_c3 = train_data_iris[100:149]
    
    xi = data_iris[i][1:5]
    label = data_iris[i][0]
    X_c1 = train_data_iris_c1[:,1:5]
    X_c2 = train_data_iris_c2[:,1:5]
    X_c3 = train_data_iris_c3[:,1:5]
    
    mu1_iris = np.array([np.mean(X_c1, 0)])
    mu2_iris = np.array([np.mean(X_c2, 0)])
    mu3_iris = np.array([np.mean(X_c3, 0)])
        
    dist_c1 = euclidean(xi, mu1_iris)
    dist_c2 = euclidean(xi, mu2_iris)
    dist_c3 = euclidean(xi, mu3_iris)
    
    c_pr = np.argmin([dist_c1, dist_c2, dist_c3]) + 1
    
    if (c_pr != label):
            print('With MMD,  sample no.{}, from class {} incorrectly classified to class {}'
                  .format(i + 1, label, c_pr))
            confusion_iris_MMD[label - 1][c_pr - 1] += 1
            
for i in range(3):
    confusion_iris_MMD[i][i] = 50 - np.sum(confusion_iris_MMD[i])
    
confusion_matrix_iris_MMD = pd.DataFrame(confusion_iris_MMD, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for MMD is:')
    print(confusion_matrix_iris_MMD)
    
print('\nThe error rate of MMDis: ', (150 - np.trace(confusion_iris_MMD))/150)

With MMD,  sample no.51, from class 2 incorrectly classified to class 3
With MMD,  sample no.53, from class 2 incorrectly classified to class 3
With MMD,  sample no.77, from class 2 incorrectly classified to class 3
With MMD,  sample no.78, from class 2 incorrectly classified to class 3
With MMD,  sample no.84, from class 2 incorrectly classified to class 3
With MMD,  sample no.107, from class 3 incorrectly classified to class 2
With MMD,  sample no.114, from class 3 incorrectly classified to class 2
With MMD,  sample no.120, from class 3 incorrectly classified to class 2
With MMD,  sample no.122, from class 3 incorrectly classified to class 2
With MMD,  sample no.127, from class 3 incorrectly classified to class 2
With MMD,  sample no.128, from class 3 incorrectly classified to class 2
With MMD,  sample no.139, from class 3 incorrectly classified to class 2

 Confusion matrix for MMD is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           50.0            0.0            0.0
c2(actual)            0.0           45.0            5.0
c3(actual)            0.0            7.0           43.0

The error rate of MMDis:  0.08

## Excercise 2 - Liquid data

In [8]:
df = pd.read_fwf('Liquid-Data_dat.txt', header=None)
data_liquid = df.to_numpy()

confusion_liquid_MMD = np.zeros((3, 3))
for i in range(178):
    train_data_liquid = np.delete(data_liquid, (i), axis=0)
    if (i < 59):
        train_data_liquid_c1 = train_data_liquid[0:58]
        train_data_liquid_c2 = train_data_liquid[58:129]
        train_data_liquid_c3 = train_data_liquid[129:177]
    elif (i >= 59 and i < 130):
        train_data_liquid_c1 = train_data_liquid[0:59]
        train_data_liquid_c2 = train_data_liquid[59:129]
        train_data_liquid_c3 = train_data_liquid[129:177]
    else:
        train_data_liquid_c1 = train_data_liquid[0:59]
        train_data_liquid_c2 = train_data_liquid[59:130]
        train_data_liquid_c3 = train_data_liquid[130:177]
    
    xi = data_liquid[i][1:7]
    label = data_liquid[i][0]
    X_c1 = train_data_liquid_c1[:,1:7]
    X_c2 = train_data_liquid_c2[:,1:7]
    X_c3 = train_data_liquid_c3[:,1:7]
    
    mu1_liquid = np.array([np.mean(X_c1, 0)])
    mu2_liquid = np.array([np.mean(X_c2, 0)])
    mu3_liquid = np.array([np.mean(X_c3, 0)])
        
    dist_c1 = euclidean(xi, mu1_liquid)
    dist_c2 = euclidean(xi, mu2_liquid)
    dist_c3 = euclidean(xi, mu3_liquid)
    
    c_pr = np.argmin([dist_c1, dist_c2, dist_c3]) + 1
    
    if (c_pr != label):
            print('With MMD,  sample no.{}, from class {} incorrectly classified to class {}'
                  .format(i + 1, label, c_pr))
            confusion_liquid_MMD[label - 1][c_pr - 1] += 1
            
confusion_liquid_MMD[0][0] = 59 - np.sum(confusion_liquid_MMD[0])
confusion_liquid_MMD[1][1] = 71 - np.sum(confusion_liquid_MMD[1])
confusion_liquid_MMD[2][2] = 48 - np.sum(confusion_liquid_MMD[2])

confusion_matrix_liquid_MMD = pd.DataFrame(confusion_liquid_MMD, index=['c1(actual)', 'c2(actual)', 'c3(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)', 'c3(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for MMD is:')
    print(confusion_matrix_liquid_MMD)
    
print('\nThe error rate of MMDis: ', (178 - np.trace(confusion_liquid_MMD))/178)

With MMD,  sample no.5, from class 1 incorrectly classified to class 3
With MMD,  sample no.21, from class 1 incorrectly classified to class 3
With MMD,  sample no.22, from class 1 incorrectly classified to class 3
With MMD,  sample no.26, from class 1 incorrectly classified to class 2
With MMD,  sample no.40, from class 1 incorrectly classified to class 3
With MMD,  sample no.41, from class 1 incorrectly classified to class 3
With MMD,  sample no.44, from class 1 incorrectly classified to class 2
With MMD,  sample no.62, from class 2 incorrectly classified to class 3
With MMD,  sample no.74, from class 2 incorrectly classified to class 1
With MMD,  sample no.84, from class 2 incorrectly classified to class 3
With MMD,  sample no.96, from class 2 incorrectly classified to class 1
With MMD,  sample no.131, from class 3 incorrectly classified to class 2
With MMD,  sample no.152, from class 3 incorrectly classified to class 2
With MMD,  sample no.154, from class 3 incorrectly classified to class 2
With MMD,  sample no.159, from class 3 incorrectly classified to class 2
With MMD,  sample no.160, from class 3 incorrectly classified to class 2
With MMD,  sample no.167, from class 3 incorrectly classified to class 2
With MMD,  sample no.168, from class 3 incorrectly classified to class 2
With MMD,  sample no.176, from class 3 incorrectly classified to class 2

 Confusion matrix for MMD is:
            c1(predicted)  c2(predicted)  c3(predicted)
c1(actual)           52.0            2.0            5.0
c2(actual)            2.0           67.0            2.0
c3(actual)            0.0            8.0           40.0

The error rate of MMDis:  0.10674157303370786

## Excercise 2 - Normal data

In [9]:
df_train = pd.read_fwf('Normal-Data-Training_dat.txt', header=None)
df_test = pd.read_fwf('Normal-Data-Testing_dat.txt', header=None)

data_normal_train = df_train.to_numpy()
data_normal_test = df_test.to_numpy()

data_normal_train_c1 = data_normal_train[0: 500]
data_normal_train_c2 = data_normal_train[500: 1000]

confusion_normal_MMD = np.zeros((2, 2))

X_c1 = data_normal_train_c1[:,1:3]
X_c2 = data_normal_train_c2[:,1:3]

mu1_normal = np.array([np.mean(X_c1, 0)])
mu2_normal = np.array([np.mean(X_c2, 0)])

for i in range(1000):
    xi = data_normal_test[i][1:3]
    label = int(data_normal_test[i][0])
    
    dist_c1 = euclidean(xi, mu1_normal)
    dist_c2 = euclidean(xi, mu2_normal)
    
    c_pr = np.argmin([dist_c1, dist_c2]) + 1
    
    if (c_pr != label):
            print('With MMD,  sample no.{}, from class {} incorrectly classified to class {}'
                  .format(i + 1, label, c_pr))
            confusion_normal_MMD[label - 1][c_pr - 1] += 1
            
for i in range(2):
    confusion_normal_MMD[i][i] = 500 - np.sum(confusion_normal_MMD[i])
    
confusion_matrix_normal_MMD = pd.DataFrame(confusion_normal_MMD, index=['c1(actual)', 'c2(actual)'],
                                columns=['c1(predicted)', 'c2(predicted)'])

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    print('\n Confusion matrix for MMD is:')
    print(confusion_matrix_normal_MMD)
    
print('\nThe error rate of MMD is: ', (1000 - np.trace(confusion_normal_MMD))/1000)

With MMD,  sample no.11, from class 1 incorrectly classified to class 2
With MMD,  sample no.16, from class 1 incorrectly classified to class 2
With MMD,  sample no.25, from class 1 incorrectly classified to class 2
With MMD,  sample no.37, from class 1 incorrectly classified to class 2
With MMD,  sample no.66, from class 1 incorrectly classified to class 2
With MMD,  sample no.94, from class 1 incorrectly classified to class 2
With MMD,  sample no.98, from class 1 incorrectly classified to class 2
With MMD,  sample no.120, from class 1 incorrectly classified to class 2
With MMD,  sample no.133, from class 1 incorrectly classified to class 2
With MMD,  sample no.134, from class 1 incorrectly classified to class 2
With MMD,  sample no.148, from class 1 incorrectly classified to class 2
With MMD,  sample no.151, from class 1 incorrectly classified to class 2
With MMD,  sample no.154, from class 1 incorrectly classified to class 2
With MMD,  sample no.197, from class 1 incorrectly classified to class 2
With MMD,  sample no.211, from class 1 incorrectly classified to class 2
With MMD,  sample no.214, from class 1 incorrectly classified to class 2
With MMD,  sample no.221, from class 1 incorrectly classified to class 2
With MMD,  sample no.229, from class 1 incorrectly classified to class 2
With MMD,  sample no.269, from class 1 incorrectly classified to class 2
With MMD,  sample no.295, from class 1 incorrectly classified to class 2
With MMD,  sample no.298, from class 1 incorrectly classified to class 2
With MMD,  sample no.318, from class 1 incorrectly classified to class 2
With MMD,  sample no.347, from class 1 incorrectly classified to class 2
With MMD,  sample no.376, from class 1 incorrectly classified to class 2
With MMD,  sample no.377, from class 1 incorrectly classified to class 2
With MMD,  sample no.380, from class 1 incorrectly classified to class 2
With MMD,  sample no.398, from class 1 incorrectly classified to class 2
With MMD,  sample no.451, from class 1 incorrectly classified to class 2
With MMD,  sample no.465, from class 1 incorrectly classified to class 2
With MMD,  sample no.481, from class 1 incorrectly classified to class 2
With MMD,  sample no.486, from class 1 incorrectly classified to class 2
With MMD,  sample no.490, from class 1 incorrectly classified to class 2
With MMD,  sample no.491, from class 1 incorrectly classified to class 2
With MMD,  sample no.492, from class 1 incorrectly classified to class 2
With MMD,  sample no.510, from class 2 incorrectly classified to class 1
With MMD,  sample no.515, from class 2 incorrectly classified to class 1
With MMD,  sample no.529, from class 2 incorrectly classified to class 1
With MMD,  sample no.548, from class 2 incorrectly classified to class 1
With MMD,  sample no.553, from class 2 incorrectly classified to class 1
With MMD,  sample no.571, from class 2 incorrectly classified to class 1
With MMD,  sample no.577, from class 2 incorrectly classified to class 1
With MMD,  sample no.582, from class 2 incorrectly classified to class 1
With MMD,  sample no.598, from class 2 incorrectly classified to class 1
With MMD,  sample no.629, from class 2 incorrectly classified to class 1
With MMD,  sample no.641, from class 2 incorrectly classified to class 1
With MMD,  sample no.646, from class 2 incorrectly classified to class 1
With MMD,  sample no.691, from class 2 incorrectly classified to class 1
With MMD,  sample no.717, from class 2 incorrectly classified to class 1
With MMD,  sample no.741, from class 2 incorrectly classified to class 1
With MMD,  sample no.747, from class 2 incorrectly classified to class 1
With MMD,  sample no.787, from class 2 incorrectly classified to class 1
With MMD,  sample no.790, from class 2 incorrectly classified to class 1
With MMD,  sample no.791, from class 2 incorrectly classified to class 1
With MMD,  sample no.833, from class 2 incorrectly classified to class 1
With MMD,  sample no.836, from class 2 incorrectly classified to class 1
With MMD,  sample no.846, from class 2 incorrectly classified to class 1
With MMD,  sample no.850, from class 2 incorrectly classified to class 1
With MMD,  sample no.852, from class 2 incorrectly classified to class 1
With MMD,  sample no.871, from class 2 incorrectly classified to class 1
With MMD,  sample no.886, from class 2 incorrectly classified to class 1
With MMD,  sample no.909, from class 2 incorrectly classified to class 1
With MMD,  sample no.912, from class 2 incorrectly classified to class 1
With MMD,  sample no.917, from class 2 incorrectly classified to class 1
With MMD,  sample no.940, from class 2 incorrectly classified to class 1
With MMD,  sample no.963, from class 2 incorrectly classified to class 1
With MMD,  sample no.964, from class 2 incorrectly classified to class 1
With MMD,  sample no.969, from class 2 incorrectly classified to class 1
With MMD,  sample no.983, from class 2 incorrectly classified to class 1

 Confusion matrix for MMD is:
            c1(predicted)  c2(predicted)
c1(actual)          466.0           34.0
c2(actual)           34.0          466.0

The error rate of MMD is:  0.068